services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - BASE_DIR=/app
      - FILES_DIR=/app/files
    volumes:
      - ./files:/app/files

  pgdb:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./api/routers/event/event.sql:/docker-entrypoint-initdb.d/event.sql
      - ./api/routers/participant/participant.sql:/docker-entrypoint-initdb.d/participant.sql
